In [1]:
import pandas as pd
import pickle
from sklearn.preprocessing import LabelEncoder
import warnings
warnings.filterwarnings("ignore")

In [2]:
def label_encode(data,attribute):
    country=LabelEncoder() #data extracted from linkedin consist of only the following country
    country.fit(["High Income" , "Upper Middle Income" , "Lower Income"])
    
    size_category=LabelEncoder()#labels of size
    size_category.fit(['large enterprise', 'small and medium-sized enterprises'])
    
    category=LabelEncoder()#labels of category
    category.fit(['CB', 'CC', 'CH', 'EP', 'H', 'R', 'TA', 'TB', 'TO', 'WP'])
    
    
    if attribute=="country":
        return country.transform(data["country_category"])
    elif attribute=="size":
        return size_category
    elif attribute=="category":
        return category.transform(data["Category"])
    else:
        print("Invalid argument")
        
def prediction(dataframe):
    dataframe_final=dataframe.copy()
    dataframe["country_encoded"]=label_encode(dataframe,"country")
    dataframe["category_encoded"]=label_encode(dataframe,"category")
    size_encoder=label_encode(dataframe,"size")
    df_model=dataframe[["Rank","country_encoded","category_encoded"]]
    dump_file = 'automl.dump.pkl'
    model = pickle.load(open(dump_file, 'rb'))
    predictions=model.predict(df_model)
    dataframe_final["Predicted Size Category"]=size_encoder.inverse_transform(predictions)
    return dataframe_final

In [3]:
df=pd.read_csv("predict.csv")

In [4]:
prediction(df)

[WARNING] [11:37:14:autosklearn.util.backend] Could not delete output dir: /tmp/autosklearn_output_13828_7253
[WARNING] [11:37:14:autosklearn.util.backend] Could not delete tmp dir: /tmp/autosklearn_tmp_13828_7253

,Company,Category,Country,country_category,Rank,Predicted Size Category
0,Barcelona Convention Bureau,CB,spain,High Income,186,small and medium-sized enterprises
1,Belgium - Visit.Brussels Convention Bureau,CB,belgium,High Income,150,small and medium-sized enterprises
2,Cologne Convention Bureau – Kölntourismus Gmbh,CB,germany,High Income,182,small and medium-sized enterprises
3,Convention Bureau Düsseldorf,CB,germany,High Income,182,small and medium-sized enterprises
4,Convention Bureau Lower Austria,CB,austria,High Income,177,small and medium-sized enterprises
5,Convention Bureau Upper Austria,CB,austria,High Income,177,small and medium-sized enterprises
6,Czechtourism - Czech Convention Bureau,CB,czech republic,High Income,153,small and medium-sized enterprises
7,Edinburgh Conference Centre,CC,united kingdom,High Income,181,small and medium-sized enterprises
8,Helsinki Convention Bureau,CB,finland,High Income,114,small and medium-sized enterprises
9,Luxembourg For Tourism,TO,luxembourg,High Income,81,small and medium-sized enterprises
10,Montenegro Convention Bureau,CB,montenegro,Upper Middle Income,100,small and medium-sized enterprises
11,Paris Convention& Visitors Bureau,CB,france,High Income,188,small and medium-sized enterprises
12,Poland Convention Bureau Polish Tourist Organi...,CB,poland,High Income,169,small and medium-sized enterprises
13,Prague Congress Centre,CC,czech republic,High Income,153,small and medium-sized enterprises
14,Salzburg Congress,CC,austria,High Income,177,small and medium-sized enterprises
15,Slovenian Convention Bureau,CB,slovenia,High Income,117,small and medium-sized enterprises
16,Visit Wales,TO,united kingdom,High Income,181,small and medium-sized enterprises
17,Visitberlin Berlin Convention Office,CB,germany,High Income,182,small and medium-sized enterprises
18,Visitoslo - Oslo Visitors And Convention Bureau,CB,norway,High Income,139,small and medium-sized enterprises
19,Visitscotland Business Events,CB,united kingdom,High Income,181,small and medium-sized enterprises
20,Wales International Convention Centre,CB,united kingdom,High Income,181,small and medium-sized enterprises
21,Warsaw Convention Bureau,CB,poland,High Income,169,small and medium-sized enterprises
22,NÜRNBERG CONVENTION BUREAU,CB,germany,High Income,182,small and medium-sized enterprises
23,ITALY - CONVENTION BUREAU ITALIA,CB,italy,High Income,184,small and medium-sized enterprises
24,KRAKOW CONVENTION BUREAU,CB,poland,High Income,169,small and medium-sized enterprises
25,MALLORCA CONVENTION BUREAU,CB,spain,High Income,186,small and medium-sized enterprises
26,"ZÜRICH TOURISM, CONVENTION BUREAU",CB,switzerland,High Income,154,small and medium-sized enterprises
27,LEIDEN CONVENTION BUREAU,CB,netherlands,High Income,167,small and medium-sized enterprises
28,LILLE CONVENTION BUREAU,CB,france,High Income,188,small and medium-sized enterprises
29,Dubrovnik Convention Bureau,CB,croatia,High Income,164,small and medium-sized enterprises
...,...,...,...,...,...,...
466,DIT Majestic Beach Resort,R,bulgaria,Upper Middle Income,147,small and medium-sized enterprises
467,Les Fleurs Boutique Hotel,H,bulgaria,Upper Middle Income,147,small and medium-sized enterprises
468,Mimosa Sunshine hotel,H,bulgaria,Upper Middle Income,147,small and medium-sized enterprises
469,Grifid Hotels,H,bulgaria,Upper Middle Income,147,small and medium-sized enterprises
470,FPI Hotels & resorts,CH,bulgaria,Upper Middle Income,147,small and medium-sized enterprises
471,Hotel Niky,H,bulgaria,Upper Middle Income,147,small and medium-sized enterprises
472,Barceló Hotel group,CH,spain,High Income,186,large enterprise
473,Holiday Inn Sofia - part of IHG hotels,H,bulgaria,Upper Middle Income,147,small and medium-sized enterprises
474,Sol Nessebar Mare - part of Melia hot Int,H,bulgaria,Upper Middle Income,147,small and medium-sized enterprises
475,Hotel Gurko,H,bulgaria,Upper Middle Income,147,small and medium-sized enterprises
476,Best Western Plus Bristol Hotel,H,bulgaria,Upper Middle Income,147,small and medium-sized enterprises
477,8 1/2 Art Guest House,H,bulgaria,Upper Middle Income,147,small and medium-sized enterprises
478,Remarkable Rwanda,TB,rwanda,Lower Income,78,small and medium-sized enterprises
479,"The Galadari hotel, Colombo, Sri Lanka.",H,sri lanka,Lower Income,109,large enterprise
480,Sri Lankan Footprints,TA,sri lanka,Lower Income,109,small and medium-sized enterprises
481,Cyprus high Commission,TA,cyprus,High Income,125,small and medium-sized enterprises
482,Osaka Conventional and Tourism Bhutan,TB,bhutan,Lower Income,33,small and medium-sized enterprises
483,SRI LANKA TOURISM PROMOTION BUREAU,TB,sri lanka,Lower Income,109,small and medium-sized enterprises
484,Lama Tours,TA,uae,High Income,148,small and medium-sized enterprises
485,Discovery Travel and Tourism,TA,uae,High Income,148,small and medium-sized enterprises
486,Zagreb Tourist Board,TB,croatia,High Income,164,small and medium-sized enterprises
487,HYPERION HOTEL BASEL,H,switzerland,High Income,154,small and medium-sized enterprises
488,ABBIT MEETING INNOCATION,H,belgium,High Income,150,small and medium-sized enterprises
489,ACCOR THE NETHERLANDS,CH,netherlands,High Income,167,large enterprise
490,ACCORHOTELS BELGIUM,H,belgium,High Income,150,small and medium-sized enterprises
491,AMSTERDAM MARRIOTT HOTELS,H,netherlands,High Income,167,large enterprise
492,APOLLO HOTELS,H,netherlands,High Income,167,large enterprise
493,CARLTON AMBASSADOR,H,netherlands,High Income,167,large enterprise
494,CROWNE PLAZA AMSTERDAM SCHIPHOL & HOLIDAY INN ...,H,netherlands,High Income,167,large enterprise
495,HILTON BELGIUM,H,belgium,High Income,150,small and medium-sized enterprises